### ISSUE TITLE
Cannot run simulator camera in conda environment

### ISSUE THREAD

**Issue by jordiandreu** [esrf-bliss/Lima#100]
I'm trying to start a simulator camera using the TANGO layer using a conda environment.
The environment is created using the yaml file:

```
 name: lima_py37
 channels:
   - esrf-bcu
   - conda-forge
 dependencies:
   - python=3.7
   - lima-core
   - lima-camera-simulator
   - lima-camera-simulator-tango
   - lima-tango-server

```

The traceback when trying to start the server is

```
$ LimaCCDs simulator -v4
Traceback (most recent call last):
  File "/homelocal/sicilia/miniconda3/envs/lima_py37/bin/LimaCCDs", line 25, in <module>
    from Lima.Server.LimaCCDs import main
  File "/homelocal/sicilia/miniconda3/envs/lima_py37/lib/python3.7/site-packages/Lima/Server/LimaCCDs.py", line 69, in <module>
    from Lima import Core
  File "/homelocal/sicilia/miniconda3/envs/lima_py37/lib/python3.7/site-packages/Lima/Core/__init__.py", line 24, in <module>
    from limacore import *
ImportError: /homelocal/sicilia/miniconda3/envs/lima_py37/lib/python3.7/site-packages/../../liblimacore.so.1.8: undefined symbol: _ZNK2H510H5Location4linkE10H5L_type_tRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_
```

Any hint about this missing symbol?

Many thanks in advance,

**Comment by sdebionne** [comment]
Hi Jordi,
I can repro the issue, I am looking into this. It has to do with the C++ API of HDF5. I guess it was not compiled with C++11 on `conda-forge` (and C++11 breaks ABI on `std::string`).

```
$ c++filt _ZNK2H510H5Location4linkE10H5L_type_tRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_

H5::H5Location::link(H5L_type_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
``````

**Comment by sdebionne** [comment]
My assumption was correct, so the fixe is simple: get the `hdf5` package from the default channel:

```
conda update hdf5
```

Note that we are not using `conda-forge` to build our conda packages. Someday Conda might introduce variants for C++ standards but we are not there yet...

**Comment by sdebionne** [comment]
And by the way, your yaml file could be as simple as:

```yaml
 name: lima_py37
 channels:
   - esrf-bcu
 dependencies:
   - python=3.7
   - lima-camera-simulator-tango
````

**Comment by jordiandreu** [comment]
Many thanks. I added the _defaults_ channel to get the correct _hdf5_ package.

**Comment by jordiandreu** [comment]
BTW, I have seen the package is not compiled with the cbf option, it is right?

**Comment by jordiandreu** [comment]
Using the suggested yaml file in a new machine and after cleaning the conda folders (conda clean --all) I cannot run the server:

```
> jandreu@pc263:~/Development/conda_envs (master)$ conda env create -f lima_py37.yml 
> Collecting package metadata: done
> Solving environment: done
> 
> Downloading and Extracting Packages
> mkl_random-1.0.2     | 405 KB    | 
> sip-4.19.8           | 290 KB    | 
> pillow-6.0.0         | 624 KB    | 
> certifi-2019.3.9     | 155 KB    | 
> pyzmq-17.1.2         | 454 KB    | 
> python-3.7.3         | 36.7 MB   | 
> blas-1.0             | 6 KB      | 
> pytango-9.2.5        | 2.1 MB    | 
> pip-19.0.3           | 1.8 MB    | 
> sqlite-3.28.0        | 1.9 MB    | 
> numpy-base-1.16.3    | 4.3 MB    | 
> lima-core-1.8.0      | 1.0 MB    | 
> omniorb-4.2.2        | 5.0 MB    | 
> olefile-0.46         | 48 KB     | 
> libedit-3.1.20181209 | 188 KB    | 
> py-boost-1.67.0      | 302 KB    | 
> lima-camera-simulato | 142 KB    | 
> wheel-0.33.1         | 39 KB     | 
> mkl_fft-1.0.10       | 169 KB    | 
> processlib-1.6.0     | 266 KB    | 
> setuptools-41.0.0    | 641 KB    | 
> boost-1.67.0         | 11 KB     | 
> numpy-1.16.3         | 49 KB     
```

```
(lima_py37) jandreu@pc263:~/Development/conda_envs (master)$ LimaCCDs 
Traceback (most recent call last):
  File "/local/miniconda3/envs/lima_py37/bin/LimaCCDs", line 25, in <module>
    from Lima.Server.LimaCCDs import main
ModuleNotFoundError: No module named 'Lima.Server'

```

**Comment by jordiandreu** [comment]
Sorry, this was an error in my PYTHONPATH, sorry for any inconvenience.
I close this issue.
