### ISSUE TITLE
package dependencies

### ISSUE THREAD

**Issue by PhilLAL** [esrf-bliss/Lima#135]
Hello,
we recently noticed that while starting Simulator device, it crashes with following error:
```
$ LimaCCDs simulator_0000 -v4
Warning optional camera Simulator can't be load, dependency not satisfied.
Traceback (most recent call last):
  File "/home/lima/miniconda3/lib/python3.9/site-packages/Lima/Server/LimaCCDs.py", line 2544, in declare_camera_n_commun_to_tango_world
    m = get_camera_module(module_name)
  File "/home/lima/miniconda3/lib/python3.9/site-packages/Lima/Server/EnvHelper.py", line 451, in get_camera_module
    return _import(mod_name)
  File "/home/lima/miniconda3/lib/python3.9/site-packages/Lima/Server/EnvHelper.py", line 429, in _import
    __import__(name)
  File "/home/lima/miniconda3/lib/python3.9/site-packages/Lima/Server/camera/Simulator.py", line 32, in <module>
    from Lima import Simulator as SimuMod
  File "/home/lima/miniconda3/lib/python3.9/site-packages/Lima/Simulator/__init__.py", line 23, in <module>
    from limasimulator import Simulator as _S
ImportError: libprocesslib.so.1.8: cannot open shared object file: No such file or directory

Traceback (most recent call last):
  File "/home/lima/miniconda3/lib/python3.9/site-packages/Lima/Server/LimaCCDs.py", line 2745, in _get_control
    m = get_camera_module(camera_type)
  File "/home/lima/miniconda3/lib/python3.9/site-packages/Lima/Server/EnvHelper.py", line 451, in get_camera_module
    return _import(mod_name)
  File "/home/lima/miniconda3/lib/python3.9/site-packages/Lima/Server/EnvHelper.py", line 429, in _import
    __import__(name)
  File "/home/lima/miniconda3/lib/python3.9/site-packages/Lima/Server/camera/Simulator.py", line 32, in <module>
    from Lima import Simulator as SimuMod
  File "/home/lima/miniconda3/lib/python3.9/site-packages/Lima/Simulator/__init__.py", line 23, in <module>
    from limasimulator import Simulator as _S
ImportError: libprocesslib.so.1.8: cannot open shared object file: No such file or directory
-------> Received a DevFailed exception: DevFailed[
DevError[
    desc = AttributeError: 'NoneType' object has no attribute 'saving'
           
  origin = Traceback (most recent call last):
  File "/home/lima/miniconda3/lib/python3.9/site-packages/tango/device_class.py", line 569, in __DeviceClass__device_factory
    device = self._new_device(deviceImplClass, klass, dev_name)
  File "/home/lima/miniconda3/lib/python3.9/site-packages/tango/device_class.py", line 548, in __DeviceClass__new_device
    return klass(dev_class, dev_name)
  File "/home/lima/miniconda3/lib/python3.9/site-packages/Lima/Server/LimaCCDs.py", line 398, in __init__
    self.init_device()
  File "/home/lima/miniconda3/lib/python3.9/site-packages/Lima/Core/Debug.py", line 64, in real_fn
    return new_fn(*arg, **kw)
  File "/home/lima/miniconda3/lib/python3.9/site-packages/Lima/Server/LimaCCDs.py", line 442, in init_device
    saving = self.__control.saving()
AttributeError: 'NoneType' object has no attribute 'saving'

  reason = PyDs_PythonError
severity = ERR]
]
```

It seems needing processlib 1.8 but installed version is 1.9:
```
$ conda list | grep processlib
processlib                1.9.0            py39h7703b5b_0    esrf-bcu
```

The conda package seems to be linked to the bad library.

**Comment by laurent-claustre** [comment]
Salut Philippe,
sorry for the inconvenience, we did a mistake with processlib 1.9.0 and camera packages. So we remove from anaconda.org the packages 1.9.0 of processlib. To fix your problem you should now force the installation of processlib 1.8.X for instance:
conda install processlib=1.8.7 --force

**Comment by PhilLAL** [comment]
Thank you for the explanation Laurent.
