### ISSUE TITLE
Segmentation fault when running on debian Jessie (future debian8), Basler camera

### ISSUE THREAD

**Issue by kif** [esrf-bliss/Lima#25]
#0  0x00007fffd3c7b928 in lima::HwVideoCtrlObj::callNewImage (this=0x0,

```
data=0x20833a0 "\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017\377\017"..., width=1296, 
height=966, aVideoMode=lima::Y16) at ../../../hardware/include/HwVideoCtrlObj.h:75
```
#1  0x00007fffd3c37add in lima::Basler::Camera::_AcqThread::threadFunction (this=0x3f42e10) at BaslerCamera.cpp:553
#2  0x00007fffd447a95d in lima::Thread::staticThreadFunction (data=0x3f42e10) at ThreadUtils.cpp:273
#3  0x00007ffff7bc8062 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#4  0x00007ffff6fd9c1d in clone () from /lib/x86_64-linux-gnu/libc.so.6

**Comment by tiagocoutinho** [comment]
What version of pylon are you using?

**Comment by tiagocoutinho** [comment]
Uff, just noticed this is very old. Do you still have the problem or is it fixed?
