### ISSUE TITLE
error while launching Lima

### ISSUE THREAD

**Issue by PhilLAL** [esrf-bliss/Lima#72]
Hi again,
after installing Lima, I build it using `sudo ./install.sh --git --install-prefix=${HOME}/Lima-install simulator python pytango-server` (I checked that sip is installed as a debian package and pytango with `pip install`).

I got the following error:
```
$ python Lima-install/bin/LimaCCDs 1
Traceback (most recent call last):
  File "Lima-install/bin/LimaCCDs", line 25, in <module>
    from Lima.Server.LimaCCDs import main
  File "/usr/lib/python2.7/dist-packages/Lima/Server/LimaCCDs.py", line 69, in <module>
    from Lima import Core
  File "/usr/lib/python2.7/dist-packages/Lima/Core/__init__.py", line 24, in <module>
    from limacore import *
ImportError: /usr/lib/python2.7/dist-packages/limacore.so: undefined symbol: _ZNK4lima8CtSaving17getFormatAsStringERSsi
```

I checked and sip is installed
Do you have any idea what goes wrong?

Thank you.

**Comment by PhilLAL** [comment]
I found what was wrong: an old Lima installation was still in my LD_LIBRARY_PATH and PYTHON_PATH.
Correct those two env variable make it work.
