### ISSUE TITLE
Last image in buffer seems to not be the real last one

### ISSUE THREAD

**Issue by smaluli** [esrf-bliss/Lima#89]
Hi all,

We at LULI currently using an old version of Lima (1.4.? from 2015) and we have issues with the last image recorded…which is not always the more recent one. It causes delay in display from zero to few images with random behaviour.
We then try to install the last version of Lima and the lima-camera-basler-tango plugin (thanks to samuel) and test this install with a Basler camera on External Trigger (EXTERNAL_GATE) at a 10-second rate looking at a PC Windows clock. At the same time, we're using a LabView binding to read a part of the buffer.

And this is the result of a 20+ minutes testing which represents 151 images:

![buffer_lima](https://user-images.githubusercontent.com/39699662/52220111-6a9b0980-289e-11e9-9030-408643ea8960.jpg)

(Sorry, the two tabs rows don't match each other but it's not important).
As you can barely see (!) the first one on the left reads "16:03:21" as the 9th from the left reads "16:04:41" (aka the near real time). You can guess the getImage(-1) in Lima reads the left one: the last_image_acquired here is nb 151. And we do not have any clue to guess the no of the real last image acquired (here the nb 143 but it fluctuates from 0 to the buffer's size, randomly). You can imagine the users' state of mind when they're trying to align a laserbeam with 10Hz or 0.1Hz rate. It's very confusing even with the minimum size of buffer.

(We tried on INTERNAL_TRIGGER mode and for the minimum size of buffer (1%) but the behaviour, as not predictable, will results in the same way: randomly lost of last image.)

Is this behaviour is already known?
Thanks for any help!
Stéphane

**Comment by smaluli** [comment]
To going further and explore possible network issues, our gap in the buffer may be caused by errors in reading complete images: could it be possible that Lima records an image in another buffer's no. if one image isn't fully received from a packet lost?

**Comment by laurent-claustre** [comment]
humm, very strange. I few questions:
- are you programming a number of frames to 0 (live mode) or to N?
- did you try reading image with number getImage(N) instead of the last one (-1)?

**Comment by smaluli** [comment]
Hi Laurent,
We're programming a 0 No. of frame (acq_number_frame).
We try both (getImage -1 or N) on the LabView binding and it has a similar behaviour.

**Comment by laurent-claustre** [comment]
ok, FYI, on live mode (0 frame) the basler plugin does not stop the acquisition even if the frame is uncompleted (due to network issues), so you can get your images not corresponding to your clock timestamp. There is no read the frame timestamp for the tango server API.Instead you can activate the saving in EDF format for instance, and have a look on the file header (ascii format) and the key "time_of_day" (in second since Epoch) or "time_of_frame" (in second since the start of acquisition).

You can also, test your camera network status by acquiring N frames instead of 0, in case of failure in packet transmission, the acquisition will stop with exception.

**Comment by smaluli** [comment]
Ok Laurent,
You mean it's a normal behaviour to not move the images into the stack until the image is complete?
I'm uncertain about my hability to perform save/read the header/compare to clock timestamp at a 10Hz rate. But I'll try with a N frame instead of 0: if we could restart the the LimaCCDs each time we have an acq_status as Fault, we could loose a few images but restart with the good one.

**Comment by laurent-claustre** [comment]
@sebastien-petitdemange  did have a look on the basler code, and we now think you find a real bug when frames are not read due to network issue and when the plugin in live mode ignore the exception and just wait for the next frame without incrementing the buffer frame count.
Temporary I suggest you fix your network problem, basler should not fail transfering packets due to network speed, packet size or packet delay configuration.
Then, we will try to fix it in a reasonable delay.

**Comment by smaluli** [comment]
It's a huge step forward (and relief) for us, thank you.
You're right we have to look further in our network because we have a high rate of errors due to packets lost; we have already set the packet size/inter-delay/transmission/jumbo frame but looking closer at these values would be helpfull at least.

**Comment by smaluli** [comment]
Dear all,
A quick update from our side.
We add a scan of the Lima's buffer in our treatment:
1. compute the sum of one line per image (N images for the entire buffer, set to minimum 1%) and put the result in an array tab0;
2. at each trig, re-compute the same sum, put the result in tab1 and look for a difference between tab1 and tab0: the index of the item which as changed is the index of the real last image acquired.
We didn't go further in comparison yet, nor done a save image/control the timestamp which we supposed is too much time consuming for our purpose. We don't have stats but it looks like to work fine under our testing conditions. Some devices are already running and we're now waiting for users' feedbacks.

**Comment by laurent-claustre** [comment]
Hi Stephane,
good news on your side. On our side we're testing a new code to fix the bug when frames are missing due to network issues. We will prepare a new conda package v1.8.1 this week.
Cheers,
Laurent

**Comment by smaluli** [comment]
Thanks Laurent, sounds good!

**Comment by laurent-claustre** [comment]
Hi Stephane,
could you try this new conda package ? 
I cannot reproduce the network failures to test it here. Then I will wait for your green light to deliver the version v1.8.1
depending of your python version under conda you can dowload files here:
http://ftpserv.esrf.fr/pub/bliss/lima/lima-camera-basler-1.8.0-py27ha8d69ae_2.tar.bz2
http://ftpserv.esrf.fr/pub/bliss/lima/lima-camera-basler-1.8.0-py36ha8d69ae_2.tar.bz2
http://ftpserv.esrf.fr/pub/bliss/lima/lima-camera-basler-1.8.0-py37ha8d69ae_2.tar.bz2

then run:

conda install ./lima-camera-basler-1.8.0-py27ha8d69ae_2.tar.bz2 --force

**Comment by smaluli** [comment]
Hi Laurent,
Thank you! Unfortunately I'm not sure I can try it with the LabView binding in parallel before Friday…and I'm off next week. I'll be back to you as soon as possible.

**Comment by smaluli** [comment]
Sorry Laurent, I can not access to the none of the listed tar files, may I have another option/link? I first try with py37 version.

**Comment by smaluli** [comment]
Alright, I get it with ftp.serf.fr!

**Comment by smaluli** [comment]
Well, I'm having a bad day, maybe you could help on this report from conda?
(py27)

```
(my-camera-env) c2s@apo-bd-archive:~/anaconda2/envs/my-camera-env$ conda install  ~/Téléchargements/lima-camera-basler-1.8.0rc4-py27ha8d69ae_0.tar.bz2  --force


WARNING: The --force flag will be removed in a future conda release.
         See 'conda install --help' for details about the --force-reinstall
         and --clobber flags.


/home/c2s/anaconda2/lib/python2.7/urllib.py:1298: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return ''.join(map(quoter, s))

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/c2s/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 1002, in __call__
        return func(*args, **kwargs)
      File "/home/c2s/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/home/c2s/anaconda2/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/c2s/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/home/c2s/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 195, in install
        explicit(args_packages, prefix, verbose=not context.quiet)
      File "/home/c2s/anaconda2/lib/python2.7/site-packages/conda/misc.py", line 59, in explicit
        spec = unquote(path_to_url(expand(spec)))
      File "/home/c2s/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/decorators.py", line 59, in _memoized_func
        result = func(*args, **kwargs)
      File "/home/c2s/anaconda2/lib/python2.7/site-packages/conda/common/url.py", line 46, in path_to_url
        url = urljoin('file:', pathname2url(path))
      File "/home/c2s/anaconda2/lib/python2.7/urllib.py", line 61, in pathname2url
        return quote(pathname)
      File "/home/c2s/anaconda2/lib/python2.7/urllib.py", line 1298, in quote
        return ''.join(map(quoter, s))
    KeyError: u'\xe9'

`$ /home/c2s/anaconda2/bin/conda install /home/c2s/Téléchargements/lima-camera-basler-1.8.0rc4-py27ha8d69ae_0.tar.bz2 --force`

  environment variables:
                 CIO_TEST=<not set>
                CLASSPATH=:/usr/local/share/java/JTango.jar:/usr/local/share/java/Jive.jar:/usr/
                          local/share/java/ATKCore.jar:/usr/local/share/java/ATKWidget.jar:/usr/
                          local/share/java/hdb_configurator.jar:/usr/local/share/java/jhdbviewer
                          .jar:/usr/local/share/java/jcalendar.jar:/usr/local/share/java/HDB++.j
                          ar:/usr/local/share/java/jython.jar
        CONDA_DEFAULT_ENV=my-camera-env
                CONDA_EXE=/home/c2s/anaconda2/bin/conda
             CONDA_PREFIX=/home/c2s/anaconda2/envs/my-camera-env
    CONDA_PROMPT_MODIFIER=(my-camera-env)
         CONDA_PYTHON_EXE=/home/c2s/anaconda2/bin/python
               CONDA_ROOT=/home/c2s/anaconda2
              CONDA_SHLVL=1
            DEFAULTS_PATH=/usr/share/gconf/xfce.default.path
       GLADE_CATALOG_PATH=:
        GLADE_MODULE_PATH=:
        GLADE_PIXMAP_PATH=:
          LD_LIBRARY_PATH=:/opt/pylon5/lib64:
           MANDATORY_PATH=/usr/share/gconf/xfce.mandatory.path
                     PATH=/home/c2s/anaconda2/envs/my-camera-env/bin:/home/c2s/anaconda2/condabi
                          n:/home/c2s/bin:/home/c2s/.local/bin:/usr/local/sbin:/usr/local/bin:/u
                          sr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
               http_proxy=<set>

     active environment : my-camera-env
    active env location : /home/c2s/anaconda2/envs/my-camera-env
            shell level : 1
       user config file : /home/c2s/.condarc
 populated config files : 
          conda version : 4.6.4
    conda-build version : 3.17.6
         python version : 2.7.15.final.0
       base environment : /home/c2s/anaconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/c2s/anaconda2/pkgs
                          /home/c2s/.conda/pkgs
       envs directories : /home/c2s/anaconda2/envs
                          /home/c2s/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.4 requests/2.21.0 CPython/2.7.15 Linux/4.15.0-43-generic ubuntu/16.04.3 glibc/2.23
                UID:GID : 1002:1002
             netrc file : None
           offline mode : False
```

**Comment by laurent-claustre** [comment]
Hi, 
that's strange you try to install a package 1.8.0rc4, those I uploaded to ftp.esrf.fr are version 1.8.0 with build number 2:
http://ftpserv.esrf.fr/pub/bliss/lima/lima-camera-basler-1.8.0-py27ha8d69ae_2.tar.bz2

**Comment by smaluli** [comment]
Hi Laurent,
Thank you for your feedback, I don't understand why I get the rc4 but I try again with:
http://ftp.esrf.fr/pub/bliss/lima/ (I can't reach ftpserv.esrf.fr)
And the install doesn't end well.
I'm off for a week so I'll look at that early March. 
```
$ /home/c2s/anaconda2/bin/conda install /home/c2s/Téléchargements/lima-camera-basler-1.8.0-py27ha8d69ae_2.tar.bz2`

  environment variables:
                 CIO_TEST=<not set>
                CLASSPATH=:/usr/local/share/java/JTango.jar:/usr/local/share/java/Jive.jar:/usr/
                          local/share/java/ATKCore.jar:/usr/local/share/java/ATKWidget.jar:/usr/
                          local/share/java/hdb_configurator.jar:/usr/local/share/java/jhdbviewer
                          .jar:/usr/local/share/java/jcalendar.jar:/usr/local/share/java/HDB++.j
                          ar:/usr/local/share/java/jython.jar
        CONDA_DEFAULT_ENV=my-camera-env
                CONDA_EXE=/home/c2s/anaconda2/bin/conda
             CONDA_PREFIX=/home/c2s/anaconda2/envs/my-camera-env
    CONDA_PROMPT_MODIFIER=(my-camera-env)
         CONDA_PYTHON_EXE=/home/c2s/anaconda2/bin/python
               CONDA_ROOT=/home/c2s/anaconda2
              CONDA_SHLVL=1
            DEFAULTS_PATH=/usr/share/gconf/xfce.default.path
       GLADE_CATALOG_PATH=:
        GLADE_MODULE_PATH=:
        GLADE_PIXMAP_PATH=:
          LD_LIBRARY_PATH=:/opt/pylon5/lib64:
           MANDATORY_PATH=/usr/share/gconf/xfce.mandatory.path
                     PATH=/home/c2s/anaconda2/envs/my-camera-env/bin:/home/c2s/anaconda2/condabi
                          n:/home/c2s/bin:/home/c2s/.local/bin:/usr/local/sbin:/usr/local/bin:/u
                          sr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
               http_proxy=<set>

     active environment : my-camera-env
    active env location : /home/c2s/anaconda2/envs/my-camera-env
            shell level : 1
       user config file : /home/c2s/.condarc
 populated config files : 
          conda version : 4.6.4
    conda-build version : 3.17.6
         python version : 2.7.15.final.0
       base environment : /home/c2s/anaconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/c2s/anaconda2/pkgs
                          /home/c2s/.conda/pkgs
       envs directories : /home/c2s/anaconda2/envs
                          /home/c2s/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.4 requests/2.21.0 CPython/2.7.15 Linux/4.15.0-43-generic ubuntu/16.04.3 glibc/2.23
                UID:GID : 1002:1002
             netrc file : None
           offline mode : False
```

**Comment by laurent-claustre** [comment]
Hi,
I just try and it works fine for me:
`
wget ftp://ftp.esrf.fr/pub/bliss/lima/lima-camera-basler-1.8.0-py27ha8d69ae_2.tar.bz2
`

then:
 source ~/conda/miniconda/bin/activate lima_py2
finally:
`conda install ./lima-camera-basler-1.8.0-py27ha8d69ae_2.tar.bz2`
`Downloading and Extracting Packages`
`############################################## | 100% `
`Preparing transaction: done`
`Verifying transaction: done`
`Executing transaction: done`

To check what is installed:
`(lima_py2) lid00limace:~ % conda list |grep lima`
`# packages in environment at /users/blissadm/conda/miniconda/envs/lima_py2:`
`lima-camera-basler        1.8.0            py27ha8d69ae_2    <unknown>`
`lima-camera-basler-tango  1.8.0                         0    esrf-bcu`
`lima-core                 1.8.0            py27ha8d69ae_0    esrf-bcu`
`lima-tango-server         1.8.0                         0    esrf-bcu`

About your installation your LD_LIBRARY_PATH is set to /opt/pylon5/lib64.
Lima package lima-camera-basler installs by dependency the pylon sdk as pylon:
`(lima_py2) lid00limace:~ % conda list|grep pylon`
`pylon5-sdk                5.0.12                        0    esrf-bcu`

Be careful to not mixed library path, you should only depend on conda packages.

**Comment by smaluli** [comment]
Hi Laurent,

Sorry for the delay. I tried with two Linux environments but the result is the same: an error occured in liburl function. But I still can not download from `ftp://ftp.esrf.fr`, maybe a rights issue? But still I already have the same package so it should work.
May I ask you for another way of installation? The `conda -c esrf-bcu` style for example?

Ok for the library paths, on first installation it worked with /opt/pylon5 but I'll check that as well.
Thanks again

**Comment by laurent-claustre** [comment]
Hi Stephane,
we will update anaconda.org tomorrow with a new package for basler, I will keep you inform asap.

**Comment by smaluli** [comment]
Thanks Laurent, it'll be a great help indeed.
